### ISSUE TITLE
Autotune Compile Error

### ISSUE THREAD

**Issue by DavidPHuber** [victor-chew/filament-joiner#1]
I confess to knowing NOTHING about coding.
I have built the excellent looking filament jointer project.  I am about to start the software side now that I think I have the hardware built correctly.
Upon compiling autotune.ino I get an error "stray '\302' in program" at line 50

I did some research that suggests that I may have gotten a stray space or improper character into the sketch, but I'm unsure how I could have done that.

This is a most interesting project, and I hope I'm getting pretty close to having it functional.
Can you please provide any assistance, or a pointer in the right direction?

I'm sorry if this is happening just because of ineptitude or some skipped step.

Thanks for any assistance you can offer.

Dave

**Comment by victor-chew** [comment]
I am not sure what is the error about... 

I am using Arduino 1.8.12 on Windows 10.

Thinking maybe there was some issue with the upload, I downloaded the ZIP archive from GitHub into a separate folder.

Then I open "autotune.ino" using Arduino, select "Arduino Nano", and click "Verify/Compile". The compilation completed with no error.

Maybe you can follow the steps above and try again?

Or copy/paste entire error log. Maybe there is additional info in there that might tell us what's wrong.

**Comment by DavidPHuber** [comment]
Thank you so much for responding.
Yes.  that worked.
I successfully complied and uploaded, but am getting only gibberish from the serial monitor.
I uploaded heater with display just to see if it functioned at all.  Nothing.
I suspect I have some wiring incorrect, and am going to review/verify.

THANKS!
I'm so looking forward to getting this one working.  what a great idea and great looking implementation.
Thank you for your efforts.

Dave

**Comment by victor-chew** [comment]
Gibberish from the serial monitor typically means your baud rate on the monitor is different from the baud rate in Serial.begin(). The 2 needs to match.

As with all engineering projects, if the total doesn't work, divide-and-conquer. Break it down into simpler parts and verify that each part works independently. That will greatly increase the chances of working when you put them together.

Good luck!

**Comment by Marco-rc** [comment]
Hello, I am trying to load the Arduino-PID-Autotune-Library but I get an "Error: 13 INTERNAL: La instalación de la librería no fue exitosa: moving extracted archive to destination dir: library not valid" error.
Also, when I try to compile, after installing the other libraries, I get a "Compilation error: NTC_Thermistor.h: No such file or directory"
Is there any update of the libraries available?I really would like to use these sketches and codes for a PET bottle filament recycling project.
Thanks!
